# Generated by Django 4.1.6 on 2023-05-26 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Barang",
            fields=[
                (
                    "id_barang",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nama_barang", models.CharField(max_length=255)),
                ("jml_stok", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ormawa",
            fields=[
                (
                    "id_ormawa",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("nama_ormawa", models.CharField(max_length=255)),
                ("ketua", models.CharField(max_length=255)),
                ("no_hp", models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name="RequestPeminjaman",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jumlah", models.IntegerField(default=0)),
                ("tgl_pinjam", models.DateTimeField(default=django.utils.timezone.now)),
                ("tgl_kembali", models.DateTimeField()),
                (
                    "barang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.barang",
                    ),
                ),
                (
                    "ormawa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.ormawa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnitKerja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_unitKerja", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("setuju", "Disetujui"), ("ditolak", "Ditolak")],
                        max_length=10,
                    ),
                ),
                ("alasan", models.CharField(max_length=225)),
                (
                    "id_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.requestpeminjaman",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="ormawa",
            name="unitkerja",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="inventory.unitkerja"
            ),
        ),
    ]
