# Generated by Django 4.1.6 on 2023-06-06 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0002_remove_ormawa_ketua_ormawa_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="ormawa", name="ketua",),
        migrations.AlterField(
            model_name="ormawa",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
